export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'

export const SHOW_SET_CATEGORY_NAME_MODAL = 'SHOW_SET_CATEGORY_NAME_MODAL'
export const HIDE_SET_CATEGORY_NAME_MODAL = 'HIDE_SET_CATEGORY_NAME_MODAL'
export const SET_CATEGORY_NAME_LOADING = 'SET_CATEGORY_NAME_LOADING'
export const SET_CATEGORY_NAME_SUCCESS = 'SET_CATEGORY_NAME_SUCCESS'
export const SET_CATEGORY_NAME_FAIL = 'SET_CATEGORY_NAME_FAIL'

export const SHOW_ADD_CATEGORY_MODAL = 'SHOW_ADD_CATEGORY_MODAL'
export const HIDE_ADD_CATEGORY_MODAL = 'HIDE_ADD_CATEGORY_MODAL'
export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL'

export const CATEGORY_FORWARD = 'CATEGORY_FORWARD'
export const CATEGORY_GOBACK = 'CATEGORY_GOBACK'

export const CLEAR_CATEGORY = 'CLEAR_CATEGORY'

export const CHANGE_TEMP_CATEGORY_NAME = 'CHANGE_TEMP_CATEGORY_NAME'