export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'

export const SET_STATUS_LOGINING = 'SET_STATUS_LOGINING'
export const SET_STATUS_SUCCESS = 'SET_STATUS_SUCCESS'

export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE'

export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'