export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'

export const SAVE_PRODUCT_DETAIL_SUCCESS = 'SAVE_PRODUCT_DETAIL_SUCCESS'

export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL'

export const PRODUCT_DETAIL_CHANGE = 'PRODUCT_DETAIL_CHANGE'
